run_name: 'aicd__finetune__example_run_000' # run index name of the model to be finetuned (same as for pretraining!)
pretrained_model: 'model_best.h5'

finetune: True

dataset_root: 'AICD_strong_shadows_incl_no_change'

train_list: 'csv_files/events_strong_shadows_incl_no_change_train.csv'
val_list: 'csv_files/events_strong_shadows_incl_no_change_val.csv'
classes: 'csv_files/classes.csv'

image_size: [128,128,3]

batch_size: 1
lr: 1e-6
steps_per_epoch: 1000

epochs: 60
snapshot_period: 1
lr_scheduler_patience: 3
early_stopping_patience: 15
