run_name: 'aicd__pretrain__example_run_000' # run index name of the model to be tested (same as for training!)

dataset_root: 'AICD_strong_shadows_incl_no_change'

train_list: 'csv_files/events_strong_shadows_incl_no_change_train.csv'
val_list: 'csv_files/events_strong_shadows_incl_no_change_val.csv'
classes: 'csv_files/classes.csv'

image_size: [128,128,3]

pretrained_model: 'model_best.h5'

batch_size: 8
lr: 1e-5
steps_per_epoch: 2000

epochs: 60
snapshot_period: 1
lr_scheduler_patience: 3
early_stopping_patience: 15
